<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>JsonDiffPatch.Benchmark</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RaJsonDiffPatch\RaJsonDiffPatch.csproj" />
  </ItemGroup>

</Project>
